"""Extended blog articles 2-10 for magazine overhaul."""
from blog_articles_data import p, section, LINK_RETTE, LINK_SERVIZI, LINK_STRUTTURA, LINK_CONTATTI, LINK_GIORNATA, LINK_GALLERIA, LINK_COAZZE, ARTICLE_INDEX

EXTENDED_ARTICLES = [
    {
        "slug": "scegliere-casa-famiglia-genitori",
        "title": ARTICLE_INDEX["scegliere-casa-famiglia-genitori"]["title"],
        "meta_title": "Come scegliere casa famiglia | Guida figli",
        "meta_desc": "Come scegliere una casa famiglia per genitori autosufficienti: checklist, domande da fare, segnali da osservare ed errori da evitare a Coazze.",
        "category": "Consigli",
        "badge": "accent",
        "reading": "15 min",
        "keywords": "come scegliere casa famiglia, genitori anziani Coazze, checklist casa famiglia Valle di Susa",
        "breadcrumb": "Scegliere casa famiglia",
        "tags": ARTICLE_INDEX["scegliere-casa-famiglia-genitori"]["tags"],
        "hero": "Camera 1.avif",
        "hero_alt": "Camera accogliente in casa famiglia per anziani autosufficienti Coazze",
        "hero_caption": "Ogni camera può diventare «casa» con oggetti personali — Casa Famiglia Quercia, Coazze.",
        "inline_images": [
            {"after_section": 2, "file": "Camera 2.avif", "alt": "Camera luminosa casa famiglia anziani Valle di Susa", "caption": "Luce naturale e spazio personale: elementi da valutare durante la visita."},
            {"after_section": 5, "file": "Corridoio.avif", "alt": "Corridoio accogliente casa famiglia Coazze", "caption": "Atmosfera e suoni: osservate oltre le camere."},
        ],
        "promos": [{"after_section": 3, "type": "galleria"}, {"after_section": 5, "type": "struttura"}, {"after_section": 7, "type": "visita"}],
        "related": ["casa-famiglia-vs-rsa-differenze", "domande-figli-casa-famiglia", "inserimento-nuovo-ospite"],
        "wa_text": "Ciao, vorrei informazioni su come scegliere una casa famiglia per mio genitore",
        "intro": "La telefonata che temevate è arrivata: vostro padre ha perso l'equilibrio in cucina, o vostra madre ha ammesso che la sera le pesa troppo il silenzio in casa. Voi, figli tra i 45 e i 65 anni, lavorate, avete famiglia, e vi sentite spezzati tra gratitudine e paura di una scelta sbagliata.",
        "sections": [
            section("prima-di-iniziare", "Prima di iniziare: cosa chiedervi",
                "Prima di visitare qualsiasi struttura, fermatevi un momento. Vostro genitore è ancora <strong>autosufficiente</strong>? Cammina, mangia, si veste, gestisce le necessità quotidiane? Se sì, una casa famiglia può essere la soluzione giusta. Se i bisogni sono più complessi, potrebbe servire un percorso diverso — parlatene con il medico di famiglia.",
                "Poi chiedetevi: cosa teme di più vostro caro? La solitudine? La perdita di autonomia? L'idea di «finire in istituto»? Le risposte vi guideranno nella conversazione. Molti genitori temono di «pesare» sui figli più di quanto temano il cambiamento.",
                "Ricordate: scegliere una casa famiglia non è abbandono. È spesso il modo più rispettoso per dire «meriti di vivere bene, in un posto dove qualcuno è presente e tu resti protagonista della tua giornata»."),
            section("quando-agire", "Quando è il momento di agire",
                "La ricerca «quando mettere genitore in casa famiglia» nasce da un conflitto: amore e ritardo. Segnali comuni: solitudine cronica, pasti saltati, casa trascurata, paura di uscire, notti inquiete, vostra ansia costante. Non serve una crisi grave per iniziare a parlare.",
                "Meglio anticipare che rincorrere un'emergenza da ospedale. Un genitore che sceglie con lucidità — anche se con rammarico — si ambienta meglio di uno che viene trasferito dopo un evento traumatico.",
                "Se il genitore dice «non ancora», rispettate il tempo ma non chiudete la conversazione. Ripropone con gentilezza, portate informazioni, offrite una visita senza impegno."),
            section("checklist-domande", "Checklist: domande da fare alla struttura",
                "Quanti ospiti accogliete? Preferite numeri contenuti, dove ogni persona è conosciuta per nome. Qual è il rapporto tra operatori e ospiti? Cosa include esattamente la retta mensile? Come funzionano le visite? Esiste un periodo di ambientamento?",
                "Come comunicate con le famiglie in caso di imprevisti? Che rapporto avete con medici e farmacie del territorio? Cosa succede se le condizioni di salute cambiano? Annotate le risposte e confrontatele con calma.",
                f"Dettagli su {LINK_RETTE} e {LINK_SERVIZI}. Confrontate anche con l'articolo sulla <a href=\"/blog/casa-famiglia-vs-rsa-differenze/\">differenza tra casa famiglia e RSA</a>."),
            section("cosa-osservare", "Cosa osservare durante la visita",
                "Non guardate solo le camere — guardate l'atmosfera. C'è odore di casa o di disinfettante? Le persone che vivono lì vi sorridono o evitano lo sguardo? Gli operatori parlano con rispetto o perentoriamente?",
                f"Chiedete di vedere gli spazi comuni: salone, cucina, giardino. Immaginate vostro padre o vostra madre seduto lì, al mattino, con un caffè. Visitate {LINK_STRUTTURA} e la {LINK_GALLERIA} online prima del sopralluogo.",
                "Fate attenzione ai suoni: un brusio di conversazione è buon segno. Il silenzio assoluto, a volte, nasconde isolamento. Chiedete di pranzare se possibile: la tavola racconta molto."),
            section("errori-comuni", "Errori comuni dei figli",
                "<strong>Decidere al posto del genitore.</strong> Coinvolgetelo, anche se fa fatica ad accettare. Una scelta condivisa dura nel tempo.",
                "<strong>Confondere casa famiglia e struttura sanitaria.</strong> Se il vostro caro è autosufficiente, non serve un ambiente medicalizzato.",
                "<strong>Scegliere solo in base al prezzo.</strong> La retta conta, ma conta di più sentirsi «a casa». <strong>Rimandare la visita.</strong> Ogni mese di indecisione può essere un mese di solitudine per chi aspetta una risposta.",
                "<strong>Non coinvolgere i fratelli.</strong> Decisioni condivise alleggeriscono il peso emotivo e riducono conflitti futuri."),
            section("confronto-strutture", "Come confrontare più strutture",
                "Visitate almeno due posti. Preparate un foglio con tre colonne: struttura, inclusioni, costo. Portate vostro caro quando possibile. Lasciate tempo di assorbire, di fare domande, di esprimere preferenze senza giudizio.",
                "Non promettete «sarà come a casa» — sarà una nuova casa, con calore vero ma cambiamento vero. Onestà emotiva costruisce fiducia più delle frasi rassicuranti vuote.",
                f"Per i costi, consultate {LINK_RETTE} e l'articolo sui <a href=\"/blog/costi-retta-casa-famiglia-piemonte/\">costi in Piemonte</a>."),
            section("ruolo-famiglia", "Il ruolo della famiglia dopo l'ingresso",
                f"La casa famiglia non sostituisce voi. Resta il vostro compito essere presenti: telefonate, visite, domande su come sta andando. Ma potete farlo con serenità, sapendo che qualcuno veglia anche di notte. Scoprite la {LINK_GIORNATA} e i {LINK_SERVIZI}.",
                "Leggete anche <a href=\"/blog/visite-familiari-casa-famiglia/\">visite familiari in casa famiglia</a> e <a href=\"/blog/inserimento-nuovo-ospite/\">l'inserimento sereno</a>.",
                "Più sapete, meno immaginate scenari peggiori. La comunicazione con la struttura è parte del percorso, non un optional."),
            section("territorio", "Coazze e Valle di Susa: criteri geografici",
                f"Se il genitore ha radici in valle, restare in zona facilita visite e legami. {LINK_COAZZE} è raggiungibile da Giaveno, Avigliana, Pinerolo in pochi minuti. Leggete <a href=\"/blog/coazze-giaveno-pinerolo-servizi/\">l'area servita</a>.",
                "Distanza non è solo chilometri: è frequenza delle visite, è il nipote che passa il sabato, è la farmacia dove vostro caro è conosciuto da vent'anni.",
                "Per famiglie che vivono a Torino, Coazze resta accessibile in meno di un'ora — un investimento di tempo che ripaga in serenità."),
            section("conclusione", "Conclusione",
                "Non esiste la scelta perfetta — esiste quella giusta per questo momento. Prendetevi il tempo di visitare, parlare, ascoltare. Vostro genitore ha ancora molto da dire, e voi siete la voce che lo aiuta a farsi sentire.",
                f"<strong>Hai dubbi? Parliamoci.</strong> Siamo a Coazze, in Valle di Susa. {LINK_CONTATTI}.",
                "Ogni famiglia ha tempi diversi — rispettiamo i vostri. Basta iniziare a parlare."),
        ],
    },
    {
        "slug": "anziani-autosufficienti-coazze",
        "title": ARTICLE_INDEX["anziani-autosufficienti-coazze"]["title"],
        "meta_title": "Anziani autosufficienti Coazze | Casa famiglia",
        "meta_desc": "Anziani autosufficienti a Coazze: natura, comunità e Casa Famiglia Quercia in Valle di Susa. Guida per famiglie di Giaveno e dintorni.",
        "category": "Territorio",
        "badge": "primary",
        "reading": "14 min",
        "keywords": "anziani autosufficienti Coazze, casa famiglia Valle di Susa, vita in comunità anziani",
        "breadcrumb": "Anziani autosufficienti Coazze",
        "tags": ARTICLE_INDEX["anziani-autosufficienti-coazze"]["tags"],
        "hero": "Esterno 1.avif",
        "hero_alt": "Villa Casa Famiglia Quercia nel verde di Coazze — anziani autosufficienti Valle di Susa",
        "hero_caption": "Nel verde di Coazze, anziani autosufficienti trovano natura e comunità — Valle di Susa.",
        "inline_images": [
            {"after_section": 2, "file": "Esterno 3.avif", "alt": "Giardino e natura casa famiglia anziani Coazze", "caption": "Passeggiate nel verde: un privilegio quotidiano in valle."},
            {"after_section": 4, "file": "Camera balcone 1.avif", "alt": "Camera con balcone vista montagna Coazze anziani", "caption": "Luce e panorama: qualità della vita oltre l'assistenza."},
        ],
        "promos": [{"after_section": 2, "type": "coazze"}, {"after_section": 4, "type": "servizi"}, {"after_section": 6, "type": "galleria"}],
        "related": ["valle-di-susa-vita-anziani", "coazze-giaveno-pinerolo-servizi", "autonomia-dignita-terza-eta"],
        "wa_text": "Ciao, cerco una casa famiglia per un genitore autosufficiente a Coazze",
        "intro": "Coazze non è solo un comune sulla carta geografica. Per chi ci è nato o ci ha trascorso le estati, è odore di bosco, campanile, volti che si conoscono al bar. Quando un genitore autosufficiente inizia a pensare che la casa grande è diventata troppo vuota, restare «in valle» può essere la scelta più naturale.",
        "sections": [
            section("autosufficiente-oggi", "Cosa significa autosufficiente oggi",
                "Un ospite autosufficiente cammina da solo, mangia, si veste, gestisce l'igiene personale. Non ha bisogno di cure continue, ma può beneficiare di <strong>compagnia, sicurezza e assistenza discreta</strong> — qualcuno che dorme sotto lo stesso tetto, che prepara i pasti, che nota se qualcosa non va.",
                "Non si tratta di «non poter più fare nulla». Si tratta di non voler fare tutto da soli. La ricerca «anziani autosufficienti vita in comunità» nasce da questa verità: autonomia e solitudine non sono la stessa cosa.",
                "In casa famiglia, l'autosufficienza non viene minata — viene protetta. Nessuno vi veste se non serve; nessuno vi alza se preferite farlo da soli."),
            section("perche-coazze", "Perché Coazze per un anziano autosufficiente",
                f"Coazze sorge nella <strong>Valle di Susa</strong>, circondata da verde e aria buona. Il ritmo è umano: niente caos cittadino, ma neanche isolamento. Da qui si raggiungono Giaveno, Avigliana, Pinerolo e Torino. {LINK_COAZZE} è continuità, non esilio.",
                "Per molti anziani del territorio, restare qui significa mantenere legami con il parrucchiere, il fornaio, la chiesa del paese. I figli possono passare il sabato pomeriggio senza pianificare un'odissea.",
                "La montagna dolce offre passeggiate, luce, silenzio rispettato — e la sicurezza di una comunità che conosce i suoi abitanti."),
            section("casa-famiglia-vs-soli", "Casa famiglia vs vivere soli in valle",
                "Vivere soli in una casa di montagna può essere romantico finché va tutto bene. Poi arriva la notte lunga, la paura di scivolare in bagno, la televisione accesa solo per sentire una voce.",
                f"Una casa famiglia a Coazze offre convivialità scelta: pranzo insieme se si vuole, camera propria quando si desidera quiete. Scoprite i {LINK_SERVIZI} e la {LINK_GIORNATA}.",
                "La differenza con la solitudine non è perdere libertà: è guadagnare presenza umana senza rinunciare alla propria storia."),
            section("figli-lontano", "Per i figli che vivono lontano",
                "Molti figli lavorano a Torino o all'estero. La distanza amplifica l'ansia: «E se cade stanotte?» Sapere che vostro padre o vostra madre è in una casa curata, con persone presenti h24, vi restituisce respiro.",
                "Potete chiamare, visitare, videochiamare — senza quella colpa silenziosa che vi mangia. La casa famiglia non cancella il vostro ruolo: vi permette di amare senza esaurirvi.",
                f"Per domande pratiche, {LINK_CONTATTI}. Per capire l'area, leggete <a href=\"/blog/coazze-giaveno-pinerolo-servizi/\">Coazze, Giaveno, Pinerolo</a>."),
            section("segnali-cambiamento", "Quando valutare il cambiamento",
                "Alcuni segnali: pasti saltati, casa trascurata, chiusura nelle relazioni, paura di uscire, notti insonni. Non serve aspettare una crisi. Meglio parlare quando il vostro caro è ancora lucido e partecipe.",
                f"Consultate {LINK_RETTE} per il percorso di ingresso. Leggete <a href=\"/blog/scegliere-casa-famiglia-genitori/\">come scegliere una casa famiglia</a> se siete all'inizio del percorso.",
                "Coazze accoglie chi ama la valle — non chi «non ha alternative». È una scelta positiva, non un ripiego."),
            section("vita-quotidiana", "Vita quotidiana e autonomia",
                f"Ogni giornata combina ritmi personali e momenti condivisi. Colazione quando si desidera, attività opzionali, tempo in giardino, lettura in salone. La {LINK_GIORNATA} descrive questo equilibrio.",
                f"Visitiate {LINK_STRUTTURA} e la {LINK_GALLERIA}: immaginate vostro caro in quegli spazi. L'autonomia si vede nei dettagli — non nelle promesse marketing.",
                "Assistenza h24 discreta: presente se serve, rispettosa sempre."),
            section("conclusione", "Conclusione",
                "Coazze non è una meta lontana: è casa per chi ama la montagna dolce e la comunità vera. Per un anziano autosufficiente, restare qui in casa famiglia può significare dignità, natura e calore.",
                f"<strong>Hai dubbi? Parliamoci.</strong> Venite a conoscerci in Stradale Poirino 152. {LINK_CONTATTI}.",
                "Restare in valle è spesso la scelta più coerente con una vita costruita qui."),
        ],
    },
]
