"""Extended blog articles 4-7."""
from blog_articles_data import p, section, LINK_RETTE, LINK_SERVIZI, LINK_STRUTTURA, LINK_CONTATTI, LINK_GIORNATA, LINK_GALLERIA, LINK_COAZZE, ARTICLE_INDEX

PART2 = [
    {
        "slug": "valle-di-susa-vita-anziani",
        "title": ARTICLE_INDEX["valle-di-susa-vita-anziani"]["title"],
        "meta_title": "Vita anziani Valle di Susa | Guida famiglie",
        "meta_desc": "Vita dopo i 65 anni in Valle di Susa: natura, comunità, casa famiglia e consigli per figli che cercano serenità per genitori autosufficienti.",
        "category": "Territorio",
        "badge": "primary",
        "reading": "15 min",
        "keywords": "Valle di Susa anziani, vita terza età Piemonte, casa famiglia Coazze",
        "breadcrumb": "Vita anziani Valle di Susa",
        "tags": ARTICLE_INDEX["valle-di-susa-vita-anziani"]["tags"],
        "hero": "Salone 1.avif",
        "hero_alt": "Salone luminoso casa famiglia anziani — vita serena Valle di Susa",
        "hero_caption": "Convivialità e quiete in salone: la terza età in Valle di Susa può essere piena.",
        "inline_images": [
            {"after_section": 2, "file": "Spazi Comuni.avif", "alt": "Spazi comuni accoglienti anziani Valle di Susa", "caption": "Spazi condivisi che invitano alla conversazione, non all'isolamento."},
            {"after_section": 4, "file": "Cucina 2.avif", "alt": "Cucina casa famiglia pasti genuini Valle di Susa", "caption": "Pasti di casa: un pilastro della qualità della vita in valle."},
        ],
        "promos": [{"after_section": 2, "type": "servizi"}, {"after_section": 4, "type": "coazze"}, {"after_section": 6, "type": "visita"}],
        "related": ["anziani-autosufficienti-coazze", "autonomia-dignita-terza-eta", "coazze-giaveno-pinerolo-servizi"],
        "wa_text": "Ciao, vorrei informazioni sulla vita in casa famiglia in Valle di Susa",
        "intro": "La Valle di Susa è una delle porte d'accesso alle Alpi più amate del Piemonte. Per chi ha passato qui decenni di lavoro, famiglia, passeggiate domenicali, invecchiare in valle non è una resa: è continuità. I figli che oggi vivono in città si chiedono: «Mamma starebbe meglio qui o lì?»",
        "sections": [
            section("territorio", "Il territorio che abbraccia",
                "Dalla bassa valle fino ai comuni collinari, la Susa offre boschi, prati, borghi storici come Avigliana, Susa, Bussoleno. I servizi essenziali — farmacie, medici, negozi — sono raggiungibili. Torino resta comoda per visite e controlli.",
                "Per un anziano autosufficiente, significa <strong>aria, luce, ritmi lenti</strong> senza tagliarsi fuori dal mondo. La ricerca «anziani soli cosa fare» trova qui risposte concrete: comunità, natura, strutture a misura d'uomo.",
                f"In <a href=\"/chi-siamo/\">Coazze</a>, Casa Famiglia Quercia incarna questo modello: villa familiare, non reparto sanitario."),
            section("socialita", "Socialità e comunità in valle",
                "In valle le relazioni hanno memoria. Conosci chi conosce tua sorella, il parroco saluta per nome, al mercato chiedono del nipote. Questa rete, per chi ha più di 65 anni, è medicina silenziosa contro la solitudine.",
                "In casa famiglia, questa dimensione comunitaria si intreccia con convivialità quotidiana: pasti insieme, chiacchiere in salone, passeggiate in giardino. Non è isolamento in coppia forzata — è compagnia scelta.",
                "Per molti anziani, la paura non è «lasciare la casa» ma «perdere il paese». Restare in valle risponde a questo timore."),
            section("attivita", "Attività e benessere quotidiano",
                f"La valle invita al movimento dolce: passeggiate, giardinaggio, lettura al sole. Le nostre <a href=\"/servizi/\">attività</a> rispettano i ritmi di ogni ospite: chi vuole partecipare, chi preferisce la poltrona col giornale.",
                "Non servono maratone — serve stimolazione. Un puzzle in salone, una chiacchiera al tavolo, un giro nel giardino: piccoli gesti che mantengono la mente e il corpo in movimento.",
                f"La {LINK_GIORNATA} descrive come articoliamo questi momenti senza imporre ritmi da ospedale."),
            section("casa-grande", "Quando la casa diventa troppo grande",
                "Molti genitori restano nella casa di una vita «per non dare fastidio». In realtà, spesso è l'inverso: i figli dormono male pensando a scale, riscaldamento, neve sul vialetto.",
                f"Una casa famiglia in valle non cancella la storia: la continua in un contesto più leggero. Visitate {LINK_STRUTTURA} e immaginate vostro caro senza scale infinite da salire da solo.",
                "La casa di famiglia può restare — per visite, per memoria, per il nipote che dorme lì il weekend. Il cambiamento non è cancellazione."),
            section("famiglie-scelta", "Per le famiglie che devono scegliere",
                "Non dovete conoscere ogni comune a memoria. Chiedetevi: mio padre ama il verde? Preferisce silenzio o compagnia? Vuole restare vicino a Giaveno, Pinerolo, Avigliana?",
                "Leggete <a href=\"/blog/anziani-autosufficienti-coazze/\">anziani autosufficienti a Coazze</a> e <a href=\"/blog/coazze-giaveno-pinerolo-servizi/\">l'area servita</a>.",
                f"Quando avete domande, {LINK_CONTATTI}. Ogni famiglia ha tempi diversi — rispettiamo i vostri."),
            section("casa-famiglia-valle", "Casa famiglia come scelta di valle",
                f"{LINK_COAZZE} offre un'alternativa calda alle RSA per genitori ancora autonomi. Assistenza h24 discreta, pasti genuini, giardino, convivialità moderata.",
                f"Esplorate la {LINK_GALLERIA} e i {LINK_SERVIZI}. Confrontate con <a href=\"/blog/casa-famiglia-vs-rsa-differenze/\">casa famiglia vs RSA</a> se avete dubbi sul modello.",
                "Valle di Susa + casa famiglia: non è romanticismo — è coerenza con una vita costruita qui."),
            section("conclusione", "Conclusione",
                "Invecchiare in Valle di Susa può essere un capitolo pieno, non una parentesi grigia. Con il supporto giusto — una casa famiglia che rispetta l'autonomia — vostro genitore può respirare ancora la montagna che ama.",
                f"<strong>Hai dubbi? Parliamoci.</strong> Siamo a Coazze, cuore della valle. {LINK_CONTATTI}.",
                "La terza età in valle merita dignità, natura e presenza umana."),
        ],
    },
    {
        "slug": "visite-familiari-casa-famiglia",
        "title": ARTICLE_INDEX["visite-familiari-casa-famiglia"]["title"],
        "meta_title": "Visite familiari casa famiglia | Consigli",
        "meta_desc": "Visite familiari in casa famiglia: come restare presenti, coinvolgere nipoti e mantenere legami forti quando un genitore vive a Coazze.",
        "category": "Famiglia",
        "badge": "accent",
        "reading": "14 min",
        "keywords": "visite familiari anziani, importanza visite genitori, casa famiglia Coazze",
        "breadcrumb": "Visite familiari",
        "tags": ARTICLE_INDEX["visite-familiari-casa-famiglia"]["tags"],
        "hero": "Sala da Pranzo + persone 2.avif",
        "hero_alt": "Pranzo conviviale con familiari — visite in casa famiglia Coazze",
        "hero_caption": "Pranzo domenicale in famiglia: le visite sono parte della vita quotidiana, non un'eccezione.",
        "inline_images": [
            {"after_section": 1, "file": "Sala da Pranzo Scenografica.avif", "alt": "Sala da pranzo accogliente per visite familiari anziani", "caption": "Tavola imbandita: le visite si integrano nella routine, non disturbano."},
            {"after_section": 4, "file": "Salone 1.avif", "alt": "Salone per visite familiari casa famiglia Valle di Susa", "caption": "Spazio comune per conversazioni lunghe e momenti con i nipoti."},
        ],
        "promos": [{"after_section": 2, "type": "giornata"}, {"after_section": 4, "type": "visita"}, {"after_section": 5, "type": "servizi"}],
        "related": ["inserimento-nuovo-ospite", "domande-figli-casa-famiglia", "scegliere-casa-famiglia-genitori"],
        "wa_text": "Ciao, vorrei sapere come funzionano le visite familiari nella vostra casa famiglia",
        "intro": "Quando un genitore si trasferisce in casa famiglia, molti figli temono una distanza emotiva: «Non sarò più il riferimento.» In realtà, la convivenza con altri non cancella il legame — lo ridisegna. Voi restate figli, confidenti, presenza.",
        "sections": [
            section("importanza", "Perché le visite familiari contano",
                "La ricerca «visite familiari anziani importanza» nasce da un bisogno profondo: non voler essere «il figlio che ha mandato via il padre». Le visite regolari trasformano la narrativa: vostro caro sa di non essere dimenticato, voi sapete di non essere sostituiti.",
                "Per un anziano, vedere il nipote, portare notizie del quartiere, condividere un pranzo — tutto questo mantiene il filo con la vita che ha costruito. La casa famiglia non è muro: è nuovo contesto dove il legame familiare continua.",
                "Studi sulla terza età confermano: relazioni familiari stabili incidono su umore, appetito, persino recupero da piccoli disturbi. Le visite non sono optional — sono cura emotiva."),
            section("orari-flessibili", "Visite senza orari rigidi",
                f"A Coazze le visite sono <strong>sempre benvenute</strong>. Non ci sono fasce orarie da rispettare con ansia. Venite quando potete: un caffè del mattino, un pranzo domenicale, un pomeriggio col nipote.",
                "Il buon senso guida: se vostro padre riposa, magari aspettate mezz'ora. Ma non serve un permesso formale. Questa flessibilità distingue la casa famiglia da molte strutture istituzionali.",
                f"Per capire i ritmi quotidiani, consultate la {LINK_GIORNATA} prima di organizzare le prime visite."),
            section("cosa-portare", "Cosa portare, cosa lasciare",
                "Portate ciò che nutre l'anima: fotografie nuove, dolci fatti in casa, notizie del quartiere. Evitate di trasformare ogni visita in un controllo sanitario o in un elenco di lamentele.",
                "Chiedete: «Com'è andata la settimana?» prima di «Hai preso le medicine?» L'ordine delle domande costruisce fiducia o la erode.",
                "Oggetti personali in camera — libri, radio, coperta — restano parte del dialogo familiare: «Ti ho portato il libro che cercavi.»"),
            section("nipoti", "I nipoti e i pronipoti",
                "I bambini portano luce negli spazi comuni. Non dovete limitare le visite per paura di «disturbare»: una casa famiglia vive anche di voci giovani. Concordate con lo staff momenti più tranquilli se il vostro caro stanca facilmente.",
                "Per i nipoti, la casa famiglia può diventare luogo di memoria positiva — non «dove è finito nonno» ma «dove andiamo il sabato». Questa percezione protegge il legame intergenerazionale.",
                f"Spazi comuni come in {LINK_STRUTTURA} sono pensati per accogliere famiglie, non solo ospiti."),
            section("equilibrio", "Equilibrio tra presenza e autonomia",
                "C'è una tentazione opposta: visitare troppo per colpa, o troppo poco per paura di invadere. La via di mezzo è regolarità senza pressione. Una telefonata breve il martedì, una visita il sabato: ritmi sostenibili per voi e rassicuranti per vostro caro.",
                f"Scoprite la {LINK_GIORNATA} per capire i momenti migliori. Leggete <a href=\"/blog/inserimento-nuovo-ospite/\">l'inserimento sereno</a> se siete nelle prime settimane.",
                "La colpa non si risolve con visite infinite — si risolve con presenza autentica e confini sani."),
            section("comunicazione", "Comunicazione con la struttura",
                f"Parlate con chi accoglie vostro padre o vostra madre ogni giorno. Condividete preferenze, anniversari, piccole abitudini. Una casa famiglia funziona quando famiglia e operatori remano dalla stessa parte. {LINK_CONTATTI} per qualsiasi dubbio.",
                "Non esiste domanda «stupida»: preferenze alimentari, orari di riposo, sensibilità a rumori — tutto conta per un inserimento sereno.",
                f"I {LINK_SERVIZI} includono assistenza discreta che integra — non sostituisce — la vostra presenza."),
            section("conclusione", "Conclusione",
                "Restare presenti non significa essere sempre fisicamente lì. Significa che vostro caro sa di non essere dimenticato. Visite, chiamate, messaggi con foto del cane: tutto tiene acceso il filo familiare.",
                f"<strong>Hai dubbi? Parliamoci.</strong> Vi aiutiamo a trovare il ritmo giusto. {LINK_CONTATTI}.",
                "Le visite familiari sono parte della cura — per vostro caro e per voi."),
        ],
    },
    {
        "slug": "costi-retta-casa-famiglia-piemonte",
        "title": ARTICLE_INDEX["costi-retta-casa-famiglia-piemonte"]["title"],
        "meta_title": "Costo casa famiglia Piemonte | Rette Coazze",
        "meta_desc": "Quanto costa una casa famiglia in Piemonte? Cosa include la retta, come confrontare offerte e orientarsi con trasparenza a Coazze e Valle di Susa.",
        "category": "Pratico",
        "badge": "accent",
        "reading": "16 min",
        "keywords": "costo casa famiglia anziani Piemonte, retta casa famiglia Coazze, prezzi casa famiglia Valle di Susa",
        "breadcrumb": "Costi e retta Piemonte",
        "tags": ARTICLE_INDEX["costi-retta-casa-famiglia-piemonte"]["tags"],
        "hero": "Cucina 1.avif",
        "hero_alt": "Cucina attrezzata casa famiglia — pasti inclusi nella retta Piemonte",
        "hero_caption": "Pensione completa inclusa: la retta copre pasti genuini preparati ogni giorno.",
        "inline_images": [
            {"after_section": 2, "file": "Camera 8.avif", "alt": "Camera singola casa famiglia retta Piemonte", "caption": "Tipologia di camera: una delle variabili che influenzano la retta mensile."},
            {"after_section": 4, "file": "Reception.avif", "alt": "Accoglienza trasparente retta casa famiglia Coazze", "caption": "Chiarezza dal primo incontro: chiedete sempre cosa è incluso."},
        ],
        "promos": [{"after_section": 1, "type": "rette"}, {"after_section": 3, "type": "servizi"}, {"after_section": 5, "type": "visita"}],
        "related": ["casa-famiglia-vs-rsa-differenze", "domande-figli-casa-famiglia", "scegliere-casa-famiglia-genitori"],
        "wa_text": "Ciao, vorrei informazioni sui costi e sulla retta della casa famiglia",
        "intro": "Parlare di soldi quando si tratta di un genitore fa male. Vorreste il meglio senza peso sulle spalle, e spesso i prezzi online sono confusi, incompleti, difficili da confrontare. Cerchiamo chiarezza sulla retta in una casa famiglia piemontese.",
        "sections": [
            section("cosa-include", "Cosa include normalmente la retta",
                "In strutture come la nostra, la retta mensile comprende in genere: alloggio in camera singola o doppia, pensione completa, assistenza h24, pulizia degli spazi personali e comuni, lavanderia, attività ricreative, utenze e Wi-Fi.",
                f"Dettagli completi in {LINK_RETTE}. La ricerca «costo casa famiglia anziani Piemonte» trova qui risposte concrete — non vaghe promesse.",
                "Chiedete sempre un preventivo scritto con voci esplicite. «Tutto incluso» senza dettaglio è spesso fonte di malintesi."),
            section("variabili", "Variabili che influenzano il prezzo",
                "La tipologia di camera incide: singola o doppia. Il luogo conta: una casa famiglia a Coazze in valle può avere costi diversi rispetto al centro di Torino. I servizi extra — accompagnamenti speciali, esigenze particolari — vanno chiesti esplicitamente.",
                "Diffidate di cifre troppo basse che non specificano cosa è incluso. Diffidate anche di cifre altissime vendute come «lusso» quando cercate semplicemente calore e cura.",
                "Confrontate RSA e casa famiglia solo se il profilo dell'ospite è comparabile — spesso non lo è. Leggete <a href=\"/blog/casa-famiglia-vs-rsa-differenze/\">casa famiglia vs RSA</a>."),
            section("confronto", "Confrontare senza stress",
                "Preparate un foglio con tre colonne: struttura, cosa include, costo mensile. Visitate almeno due posti. Chiedete se esistono soggiorni di prova. Parlate con altre famiglie se possibile.",
                "Non siete obbligati a decidere al primo incontro. Una buona struttura vi darà tempo. La fretta economica spesso maschera fretta emotiva — rallentare è legittimo.",
                f"Per orientarvi nella scelta, <a href=\"/blog/scegliere-casa-famiglia-genitori/\">come scegliere una casa famiglia</a> offre una checklist pratica."),
            section("contributi", "Contributi e agevolazioni",
                "A seconda della situazione, possono esistere contributi regionali, comunali o forme di detrazione. Informatevi presso il Comune di residenza del vostro caro e con un commercialista di fiducia.",
                "Noi vi aiutiamo con la documentazione necessaria quando possibile. Trasparenza burocratica è parte del rispetto per le famiglie.",
                "Non assumete che «non ci sono aiuti» senza aver chiesto — le normative cambiano e i casi variano."),
            section("valore", "Valore oltre il prezzo",
                "Il vero «costo» da evitare è la solitudine non interrotta, la casa vuota, le notti in cui nessuno risponde al telefono. Una retta equa compra serenità — per vostro caro e per voi.",
                f"Scoprite i {LINK_SERVIZI} inclusi. Il valore emerge quando confrontate inclusioni, non solo cifre a fondo pagina.",
                "Molti figli, mesi dopo l'ingresso, ci dicono: «Avremmo dovuto farlo prima» — non per il prezzo, ma per la qualità della vita recuperata."),
            section("coazze-economico", "Coazze: contesto economico e territoriale",
                f"{LINK_COAZZE} offre un equilibrio tra qualità e contesto: natura, comunità, accessibilità da Giaveno e Pinerolo senza costi da grande città.",
                f"Visitate {LINK_STRUTTURA} e {LINK_GALLERIA} prima di valutare solo il numero sulla retta. Atmosfera e umanità non compaiono in Excel — ma contano enormemente.",
                f"Per preventivo personalizzato, {LINK_CONTATTI} senza impegno."),
            section("conclusione", "Conclusione",
                "Trasparenza è il minimo che meritate. Chiedete, confrontate, dormiteci sopra. Scegliere con lucidità economica protegge il rapporto familiare da rancori futuri.",
                f"<strong>Hai dubbi? Parliamoci.</strong> Vi spieghiamo ogni voce con pazienza. {LINK_CONTATTI}.",
                "La retta è un investimento in dignità — non una pena da pagare in silenzio."),
        ],
    },
    {
        "slug": "inserimento-nuovo-ospite",
        "title": ARTICLE_INDEX["inserimento-nuovo-ospite"]["title"],
        "meta_title": "Inserimento casa famiglia | Come funziona",
        "meta_desc": "Inserimento in casa famiglia: come funziona l'ambientamento, oggetti personali e ruolo della famiglia. Guida per figli a Coazze, Valle di Susa.",
        "category": "Percorso",
        "badge": "primary",
        "reading": "14 min",
        "keywords": "inserimento casa famiglia come funziona, nuovo ospite anziani, ambientamento Coazze",
        "breadcrumb": "Inserimento nuovo ospite",
        "tags": ARTICLE_INDEX["inserimento-nuovo-ospite"]["tags"],
        "hero": "Ingresso 2.avif",
        "hero_alt": "Ingresso accogliente — inserimento nuovo ospite casa famiglia Coazze",
        "hero_caption": "L'ingresso accogliente: il primo passo di un inserimento sereno.",
        "inline_images": [
            {"after_section": 2, "file": "Camera 9.avif", "alt": "Camera personalizzata nuovo ospite casa famiglia", "caption": "Oggetti personali trasformano la camera in «casa»."},
            {"after_section": 4, "file": "Letto Camera 11.avif", "alt": "Letto confortevole inserimento anziani Coazze", "caption": "Comfort e familiarità: dettagli che accelerano l'ambientamento."},
        ],
        "promos": [{"after_section": 1, "type": "rette"}, {"after_section": 3, "type": "struttura"}, {"after_section": 5, "type": "visita"}],
        "related": ["visite-familiari-casa-famiglia", "scegliere-casa-famiglia-genitori", "domande-figli-casa-famiglia"],
        "wa_text": "Ciao, vorrei sapere come funziona l'inserimento di un nuovo ospite",
        "intro": "Il giorno del trasloco arriva sempre troppo presto o troppo tardi. Vostro padre impacchetta la foto del matrimonio. Vostra madre chiede se può portare la coperta di lana. Voi stringete le mani e pensate: «Starà bene?» L'inserimento, se gestito con cura, può essere dolce.",
        "sections": [
            section("prima-ingresso", "Prima dell'ingresso: il percorso",
                f"Tutto inizia con una telefonata e una visita. Poi la valutazione condivisa: siamo compatibili? Cosa serve a vostro caro? Documenti, certificato medico base, contratto chiaro. In {LINK_RETTE} trovate il percorso passo per passo.",
                "La ricerca «inserimento casa famiglia come funziona» trova qui un processo umano — non burocrazia fredda. Ogni famiglia ha tempi diversi; rispettiamo i vostri.",
                f"Prima di decidere, leggete <a href=\"/blog/scegliere-casa-famiglia-genitori/\">come scegliere una casa famiglia</a> e visitate {LINK_STRUTTURA}."),
            section("ambientamento", "Il periodo di ambientamento",
                "I primi giorni sono ascolto. Ogni ospite ha tempi diversi: qualcuno si integra subito a tavola, qualcuno preferisce mangiare in camera un paio di volte. Non forziamo. Presentiamo gli spazi, le persone, i ritmi.",
                "Voi potete visitare più spesso all'inizio — la vostra presenza è un ponte sicuro. Non è «controllare»: è accompagnare una transizione delicata.",
                f"La {LINK_GIORNATA} descrive i ritmi che vostro caro incontrerà — familiarità anticipata riduce ansia."),
            section("oggetti-personali", "Oggetti personali e spazio «suo»",
                f"Portate ciò che profuma di casa: quadri, libri, la poltrona se entra in camera, radio vecchia, piante. Lo spazio deve diventare «suo», non un hotel. In {LINK_STRUTTURA} ogni camera accoglie storie diverse.",
                "Il giorno del trasloco, evitate il caos: poche cose significative battono scatoloni anonimi. Vostro caro deve riconoscere «casa» nello spazio — non solo «camera 3».",
                f"Esplorate la {LINK_GALLERIA} per vedere come altri ospiti hanno personalizzato gli spazi."),
            section("comunicazione", "Comunicazione famiglia-struttura",
                "Condividete abitudini alimentari, preferenze, paure notturne, nomi degli affetti. Nessun dettaglio è ridicolo. Più sappiamo, meglio accogliamo.",
                "Restiamo in contatto nelle prime settimane: un messaggio, una chiamata, un «come l'avete visto oggi?» La famiglia e la struttura sono alleati, non avversari.",
                f"Per dubbi operativi, {LINK_CONTATTI}. Leggete anche <a href=\"/blog/visite-familiari-casa-famiglia/\">visite familiari</a>."),
            section("segnali-positivi", "Segnali di un buon inserimento",
                "Sorrisi spontanei, appetito regolare, curiosità verso gli altri, telefonate che raccontano piccole cose («oggi ho visto un uccellino dal salone»). Non serve euforia — serve stabilità crescente.",
                "Se dopo alcune settimane notate chiusura persistente, parlate con noi. Adattamenti sono possibili. L'inserimento non è linea fissa — è dialogo continuo.",
                "I nipoti che tornano volentieri il sabato sono spesso il termometro migliore."),
            section("ruolo-figli", "Il ruolo dei figli durante l'inserimento",
                "Non dovete «fare tutto». Portate calma, non soluzioni infinite. Ascoltate senza giudicare i primi giorni difficili. Vostro caro può lamentarsi con voi — è normale, è fiducia.",
                f"Coinvolgete fratelli e sorelle nelle visite iniziali. Messaggio coerente: «Siamo qui, insieme.» Consultate <a href=\"/blog/domande-figli-casa-famiglia/\">le domande che ogni figlio si pone</a> se la colpa vi pesa.",
                f"I {LINK_SERVIZI} supportano l'inserimento con assistenza discreta h24."),
            section("conclusione", "Conclusione",
                "Accogliere un nuovo ospite è per noi un impegno morale, non solo organizzativo. Vostro caro merita di sentirsi atteso, non depositato.",
                f"<strong>Hai dubbi? Parliamoci.</strong> Vi accompagniamo dall'inizio. {LINK_CONTATTI}.",
                "Un inserimento sereno è possibile — con tempo, oggetti personali e presenza familiare."),
        ],
    },
]
