"""Extended blog articles 8-10."""
from blog_articles_data import p, section, LINK_RETTE, LINK_SERVIZI, LINK_STRUTTURA, LINK_CONTATTI, LINK_GIORNATA, LINK_GALLERIA, LINK_COAZZE, ARTICLE_INDEX

PART3 = [
    {
        "slug": "autonomia-dignita-terza-eta",
        "title": ARTICLE_INDEX["autonomia-dignita-terza-eta"]["title"],
        "meta_title": "Autonomia e dignità terza età | Guida",
        "meta_desc": "Autonomia e dignità in terza età: perché contano per anziani autosufficienti e come una casa famiglia a Coazze le rispetta ogni giorno.",
        "category": "Valori",
        "badge": "primary",
        "reading": "15 min",
        "keywords": "autonomia anziani, dignità terza età, casa famiglia Coazze Valle di Susa",
        "breadcrumb": "Autonomia e dignità",
        "tags": ARTICLE_INDEX["autonomia-dignita-terza-eta"]["tags"],
        "hero": "Spazi Comuni.avif",
        "hero_alt": "Spazi comuni accoglienti — autonomia e dignità in terza età Coazze",
        "hero_caption": "Spazi condivisi dove l'autonomia si esprime: scegliere compagnia o quiete.",
        "inline_images": [
            {"after_section": 2, "file": "Camera 6.avif", "alt": "Camera privata autonomia anziani casa famiglia", "caption": "Privacy e autonomia: la camera come spazio personale sovrano."},
            {"after_section": 4, "file": "Scale + persona.avif", "alt": "Mobilità autonoma anziani casa famiglia Coazze", "caption": "Assistenza discreta quando serve — non controllo quotidiano."},
        ],
        "promos": [{"after_section": 2, "type": "servizi"}, {"after_section": 4, "type": "coazze"}, {"after_section": 6, "type": "galleria"}],
        "related": ["anziani-autosufficienti-coazze", "valle-di-susa-vita-anziani", "casa-famiglia-vs-rsa-differenze"],
        "wa_text": "Ciao, vorrei sapere come rispettate l'autonomia degli ospiti",
        "intro": "Quando parliamo di genitori anziani, è facile cadere nel linguaggio che toglie agency: «non può più», «bisogna decidergli noi», «ormai è fragile». Ma vostro padre che ha costruito una casa, vostra madre che ha cresciuto tre figli — non sono improvvisamente bambini. <strong>Autonomia</strong> e <strong>dignità</strong> non sono lussi: sono diritti.",
        "sections": [
            section("autonomia-non-solitudine", "Autonomia non significa solitudine",
                "Confondiamo spesso «autonomo» con «deve restare solo a casa». Un anziano autosufficiente può aver bisogno di compagnia, sicurezza, pasti preparati — e restare padrone delle proprie scelte quotidiane.",
                "Una casa famiglia protegge questa libertà meglio di una solitudine forzata. Nessuno vi veste se non serve; nessuno vi alza se preferite farlo da soli. Assistenza discreta h24: presente se serve, rispettosa sempre.",
                "Leggete <a href=\"/blog/anziani-autosufficienti-coazze/\">anziani autosufficienti a Coazze</a> per il contesto territoriale."),
            section("dignita-linguaggio", "Dignità nel linguaggio e nelle relazioni",
                "Evitate di parlare di vostro caro come assente quando è presente. Evitate decisioni totali senza ascoltarlo. In famiglia, piccoli gesti costruiscono dignità: chiedere «cosa ne pensi?» invece di annunciare.",
                f"In casa a Coazze trattiamo ogni ospite per nome, non per numero di camera. Leggete <a href=\"/chi-siamo/\">chi siamo</a> per la nostra filosofia.",
                "La dignità si vede nei dettagli: come gli operatori chiedono il permesso prima di entrare in camera, come si rispettano le preferenze al tavolo."),
            section("assistenza-discreta", "Assistenza discreta vs controllo",
                f"Essere presenti h24 non significa controllare ogni respiro. Significa essere lì se serve aiutare ad alzarsi, se c'è un imprevisto, se serve una mano con la confezione difficile. I {LINK_SERVIZI} sono pensati così: sostegno, non sostituzione.",
                "Contrasto con RSA: dove il controllo è spesso necessario per sicurezza sanitaria, in casa famiglia l'equilibrio è diverso. Per profilo autosufficiente, meno è più.",
                "Confrontate con <a href=\"/blog/casa-famiglia-vs-rsa-differenze/\">casa famiglia vs RSA</a> se il modello vi interessa."),
            section("figli-controllo", "Per i figli: lasciar andare un po' di controllo",
                "È duro. Sempre lo è stato, anche quando eravate adolescenti. Lasciar respirare vostro caro in un ambiente protetto vi sembra un tradimento — ma può essere il regalo più grande. Fidarsi non è abbandono.",
                "Molti figli cercano «senso di colpa affidare genitore» online. La risposta non è visitare ogni giorno per compensare — è scegliere bene e poi fidare con confini sani.",
                f"Leggete <a href=\"/blog/domande-figli-casa-famiglia/\">le domande che ogni figlio si pone</a> e <a href=\"/blog/visite-familiari-casa-famiglia/\">visite familiari</a>."),
            section("quotidiano", "Autonomia nella vita quotidiana",
                f"La {LINK_GIORNATA} mostra come articoliamo libertà e struttura: colazione flessibile, attività opzionali, tempo in giardino, lettura in salone. Nessun obbligo di partecipare a tutto.",
                f"Visitiate {LINK_STRUTTURA}: camere personalizzabili, spazi comuni che invitano ma non impongono. La {LINK_GALLERIA} mostra l'atmosfera concreta.",
                f"{LINK_COAZZE} in Valle di Susa: contesto che favorisce passeggiate autonome e vita di paese."),
            section("valore-famiglia", "Per la famiglia: autonomia condivisa",
                "Quando vostro caro mantiene autonomia, anche voi recuperate respiro. Non dovete essere operatori 24 ore su 24. Potete tornare a essere figli — con telefonate che non sono solo checklist mediche.",
                f"Rette trasparenti in {LINK_RETTE}. Percorso chiaro. {LINK_CONTATTI} per domande senza impegno.",
                "Autonomia del genitore e serenità dei figli sono collegati — non opposti."),
            section("conclusione", "Conclusione",
                "Invecchiare con dignità significa continuare a sentirsi persona, non carico. Una casa famiglia che rispetta l'autonomia non vi chiede di smettere di amare — vi chiede di amare in modo più saggio.",
                f"<strong>Hai dubbi? Parliamoci.</strong> Siamo qui per ascoltarvi. {LINK_CONTATTI}.",
                "Autonomia e dignità: pilastri della terza età che merita rispetto."),
        ],
    },
    {
        "slug": "coazze-giaveno-pinerolo-servizi",
        "title": ARTICLE_INDEX["coazze-giaveno-pinerolo-servizi"]["title"],
        "meta_title": "Coazze Giaveno Pinerolo | Area servita",
        "meta_desc": "Casa Famiglia Quercia serve Pinerolo, Torino, Val Chisone e Pinerolese. Distanze, visite e servizi per famiglie del territorio.",
        "category": "Territorio",
        "badge": "primary",
        "reading": "13 min",
        "keywords": "casa famiglia Coazze Valle Susa, Giaveno anziani, Pinerolo casa famiglia",
        "breadcrumb": "Area servita",
        "tags": ARTICLE_INDEX["coazze-giaveno-pinerolo-servizi"]["tags"],
        "hero": "Esterno 3.avif",
        "hero_alt": "Vista esterna Casa Famiglia Quercia — area servita Coazze Giaveno Pinerolo",
        "hero_caption": "Stradale Poirino 152, Coazze: cuore operativo, valle tutta intorno.",
        "inline_images": [
            {"after_section": 2, "file": "intro strutture.avif", "alt": "Panoramica struttura casa famiglia area Valle di Susa", "caption": "Villa familiare al centro di un territorio che conoscono le famiglie locali."},
            {"after_section": 4, "file": "Camera balcone 2.avif", "alt": "Vista dalla camera area servita Coazze Giaveno", "caption": "Dalla camera, il panorama della valle che molti ospiti conoscono da sempre."},
        ],
        "promos": [{"after_section": 1, "type": "coazze"}, {"after_section": 3, "type": "servizi"}, {"after_section": 5, "type": "visita"}],
        "related": ["anziani-autosufficienti-coazze", "valle-di-susa-vita-anziani", "costi-retta-casa-famiglia-piemonte"],
        "wa_text": "Ciao, vorrei sapere se siamo nell'area servita dalla vostra casa famiglia",
        "intro": "Siamo in Stradale Poirino 152, Coazze — ma le famiglie che ci scelgono arrivano da tutta la Valle di Susa e dai comuni limitrofi. Giaveno, Avigliana, Pinerolo, Trana, Valgioie: nomi che suonano vicini a chi vive il Piemonte occidentale.",
        "sections": [
            section("coazze-cuore", "Coazze: cuore della casa",
                f"Coazze è un comune collinare, verde, tranquillo. Qui vive la nostra casa famiglia: villa familiare, giardino, ritmi umani. {LINK_COAZZE} è continuità per chi ha radici in valle — non esilio urbano.",
                "Il centro del paese è raggiungibile a piedi. Farmacia, servizi essenziali, comunità a misura d'uomo. Per un anziano autosufficiente, restare «di zona» mantiene legami sociali vivi.",
                f"Scoprite {LINK_STRUTTURA} e la {LINK_GALLERIA} online prima della visita."),
            section("giaveno-avigliana", "Giaveno e Avigliana: vicini di valle",
                "Da Giaveno e Avigliana si raggiunge Coazze in pochi minuti di auto. Molte famiglie fanno visite settimanali senza stress: pranzo insieme il sabato, rientro a casa la sera.",
                "La vicinanza mantiene vivi i legami. Il nipote che passa il weekend, la sorella che viene per il caffè — tutto questo è realistico quando la distanza è umana, non geografica da città.",
                "Per famiglie giavenesi, siamo spesso la prima scelta «di valle» quando la solitudine del genitore diventa insostenibile."),
            section("pinerolo-valle", "Pinerolo e la valle oltre",
                "Da Pinerolo la strada attraversa paesaggi che molti anziani conoscono bene — mercati, parenti, ricordi. Anche da più lontano, restare «in zona» è spesso preferibile a un trasferimento in città caotica.",
                "Da Pinerolo a Coazze: circa 25–35 minuti in auto attraverso la Valle di Susa. Un investimento di tempo che ripaga in visite frequenti e serenità familiare.",
                "Leggete <a href=\"/blog/valle-di-susa-vita-anziani/\">vita in Valle di Susa</a> per il contesto più ampio."),
            section("trana-valgioie", "Trana, Valgioie e comuni piccoli",
                "I comuni più piccoli hanno spesso meno servizi per anziani che vivono soli. Una casa famiglia centralizzata ma immersa nel territorio offre soluzione senza allontanare troppo.",
                "Non dovete abitare Coazze per sentirvi a casa qui. Basta amare la montagna dolce, la comunità vera, la possibilità di passare quando volete.",
                f"I {LINK_SERVIZI} includono tutto ciò che serve per vivere bene senza tornare a gestire una casa grande da soli."),
            section("torino-dintorni", "Torino e provincia: raggiungibilità",
                "Da Torino centro, Coazze è raggiungibile in meno di un'ora. Per figli che lavorano in città ma hanno genitori di valle, questa accessibilità è decisiva.",
                "SS589, percorsi panoramici, abitudine al tragitto — molte famiglie torinesi scelgono Coazze per mantenere il genitore «sul territorio» senza sacrificare le visite.",
                f"Pianificate il primo incontro tramite {LINK_CONTATTI}. Visita gratuita, senza impegno."),
            section("organizzare-visite", "Come organizzare visite e contatti",
                f"Parlate con noi per pianificare il primo incontro. Info su {LINK_SERVIZI} e {LINK_CONTATTI} — telefono, WhatsApp, email.",
                "Leggete <a href=\"/blog/visite-familiari-casa-famiglia/\">visite familiari in casa famiglia</a> per organizzare presenza familiare sostenibile.",
                f"Dettagli economici in {LINK_RETTE} e <a href=\"/blog/costi-retta-casa-famiglia-piemonte/\">costi in Piemonte</a>."),
            section("conclusione", "Conclusione",
                "Non dovete abitare Coazze per sentirvi a casa qui. Basta amare la montagna dolce, la comunità vera, la possibilità di passare quando volete.",
                f"<strong>Hai dubbi? Parliamoci.</strong> Vi indichiamo il percorso migliore da dove siete. {LINK_CONTATTI}.",
                "Valle di Susa: un territorio che accoglie chi invecchia con dignità."),
        ],
    },
    {
        "slug": "domande-figli-casa-famiglia",
        "title": ARTICLE_INDEX["domande-figli-casa-famiglia"]["title"],
        "meta_title": "FAQ figli casa famiglia | Domande comuni",
        "meta_desc": "Domande dei figli sulla casa famiglia: senso di colpa, costi, visite, autonomia, RSA. Risposte oneste da Casa Famiglia Quercia, Coazze.",
        "category": "FAQ",
        "badge": "accent",
        "reading": "17 min",
        "keywords": "domande figli casa famiglia, senso di colpa affidare genitore, FAQ anziani Coazze",
        "breadcrumb": "FAQ per i figli",
        "tags": ARTICLE_INDEX["domande-figli-casa-famiglia"]["tags"],
        "hero": "Camera 9.avif",
        "hero_alt": "Camera personalizzata casa famiglia — domande figli anziani Coazze",
        "hero_caption": "Ogni domanda dei figli merita una risposta onesta — senza giri di parole.",
        "inline_images": [
            {"after_section": 2, "file": "Camera 10 (bella).avif", "alt": "Camera accogliente risposte domande figli casa famiglia", "caption": "«Starà bene?» — la camera personalizzata è parte della risposta."},
            {"after_section": 5, "file": "Bagno 1.avif", "alt": "Comfort quotidiano casa famiglia anziani autosufficienti", "caption": "Assistenza discreta e comfort: sicurezza senza istituzionalizzazione."},
        ],
        "promos": [{"after_section": 2, "type": "visita"}, {"after_section": 4, "type": "rette"}, {"after_section": 6, "type": "servizi"}],
        "related": ["casa-famiglia-vs-rsa-differenze", "scegliere-casa-famiglia-genitori", "costi-retta-casa-famiglia-piemonte"],
        "wa_text": "Ciao, ho molte domande sulla casa famiglia e vorrei parlarne con voi",
        "intro": "Di notte, quando il telefono resta muto, le domande arrivano a ondate: «Ho aspettato troppo?» «Sono un cattivo figlio?» «E se non si ambienta?» Non siete soli. Queste sono le domande che sentiamo più spesso — con risposte oneste.",
        "sections": [
            section("senso-colpa", "Sto tradendo mio padre se lo porto in casa famiglia?",
                "No. Tradimento sarebbe lasciarlo solo e spaventato. Accoglierlo in un luogo curato, con persone presenti e autonomia rispettata, è cura. Molti ospiti ci dicono mesi dopo: «Avrei dovuto farlo prima.»",
                "La ricerca «senso di colpa affidare genitore» è tra le più frequenti. La colpa non si risolve evitando la decisione — si risolve informandosi, coinvolgendo il genitore, scegliendo bene.",
                "Voi non «mandate via» — accompagnate una transizione difficile con amore. È diverso."),
            section("momento-giusto", "Come capisco se è il momento giusto?",
                "Segnali comuni: solitudine cronica, casa trascurata, pasti saltati, paura di uscire, notti inquiete, vostra ansia costante. Non serve una crisi grave. Meglio anticipare che rincorrere un'emergenza.",
                "Se il genitore dice «non ancora», rispettate il tempo ma non chiudete la conversazione. Ripropone con gentilezza, offrite una visita senza impegno.",
                "Leggete <a href=\"/blog/scegliere-casa-famiglia-genitori/\">come scegliere una casa famiglia</a> per una checklist pratica."),
            section("differenza-rsa", "Qual è la differenza con una RSA?",
                "La casa famiglia accoglie <strong>autosufficienti</strong> in ambiente familiare. Le RSA sono strutture sanitarie per bisogni più complessi. Articolo completo: <a href=\"/blog/casa-famiglia-vs-rsa-differenze/\">casa famiglia vs RSA</a>.",
                "Se vostro caro cammina, mangia da solo, non ha bisogni infermieristici quotidiani — probabilmente il profilo è casa famiglia, non RSA.",
                "Chiedere al medico di famiglia integra il vostro amore senza sostituirlo."),
            section("costi", "Quanto costa? Cosa include la retta?",
                f"La retta varia in base a camera e servizi. Noi includiamo pensione completa, assistenza h24, pulizia, lavanderia, attività. Dettagli in {LINK_RETTE} e <a href=\"/blog/costi-retta-casa-famiglia-piemonte/\">costi in Piemonte</a>.",
                "Chiedete preventivo scritto. Confrontate inclusioni, non solo cifre. Trasparenza protegge il rapporto familiare da rancori futuri.",
                "Non esiste «prezzo giusto» universale — esiste retta adeguata al profilo e alle inclusioni."),
            section("visite", "Posso visitarlo quando voglio?",
                "Sì. Le visite sono benvenute senza orari rigidi. Leggete <a href=\"/blog/visite-familiari-casa-famiglia/\">visite familiari in casa famiglia</a> per equilibrio tra presenza e autonomia.",
                "Non serve compensare con visite quotidiane per la colpa — serve presenza autentica e regolare. Una telefonata il martedì e una visita il sabato possono bastare.",
                "I nipoti sono benvenuti. La casa famiglia vive anche di voci giovani."),
            section("salute-cambia", "Cosa succede se le condizioni di salute cambiano?",
                "Parliamo con voi e valutiamo insieme. Se servono cure non compatibili, vi orientiamo con trasparenza. La comunicazione anticipata è parte del rispetto.",
                "Non promettiamo che nulla cambierà — promettiamo dialogo e accompagnamento. Questo è ciò che le famiglie meritano.",
                f"Per il percorso di ingresso, {LINK_RETTE} e <a href=\"/blog/inserimento-nuovo-ospite/\">inserimento sereno</a>."),
            section("inserimento", "Come funziona l'inserimento?",
                "Periodo di ambientamento, oggetti personali in camera, visite frequenti all'inizio. Tutto in <a href=\"/blog/inserimento-nuovo-ospite/\">inserimento sereno</a>.",
                "I primi giorni possono essere difficili — è normale. Vostro caro può lamentarsi con voi; è fiducia, non fallimento della scelta.",
                f"Visitiate {LINK_STRUTTURA} prima del trasloco per familiarità anticipata."),
            section("anziani-soli", "Mio padre è solo: cosa posso fare davvero?",
                "La ricerca «anziani soli cosa fare» nasce da urgenza reale. Opzioni: aumentare presenza familiare (se sostenibile), servizi domiciliari (limitati), casa famiglia (se autosufficiente), RSA (se fragilità elevata).",
                f"Se è autosufficiente ma isolato, {LINK_COAZZE} offre compagnia scelta e sicurezza h24. Leggete <a href=\"/blog/anziani-autosufficienti-coazze/\">anziani autosufficienti a Coazze</a>.",
                "Agire prima della crisi protegge tutti — genitore e figli."),
            section("conclusione", "Conclusione: figli che cercano il bene",
                "Non esiste figlio perfetto — esiste figlio che cerca il bene con informazioni e amore. Continuate a fare domande. È così che si protegge chi vi ha protetto.",
                f"<strong>Hai dubbi? Parliamoci.</strong> {LINK_CONTATTI} — rispondiamo con calma, senza pressione.",
                "Ogni domanda è legittima. Ogni famiglia ha tempi diversi. Siamo qui."),
        ],
    },
]
