#!/usr/bin/env python3
"""Bulk word-count top-up for blog articles under 800 words."""
import os, re, glob

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BLOG = os.path.join(BASE, "blog")

BLOCKS = {
"anziani-autosufficienti-coazze": """<h2>Un dialogo aperto con vostro caro</h2><p>Prima di proporre qualsiasi soluzione, sedetevi con calma. Chiedete: "Cosa ti manca di più?" "Cosa ti preoccupa della casa?" "Hai paura di qualcosa in particolare?" Le risposte vi sorprenderanno. A volte la paura non è il trasloco — è l'orgoglio di ammettere bisogno. A volte è la fedeltà verso chi non c'è più. Rispettate queste paure senza smontarle bruscamente.</p><p>Proponete una visita come gita, non come ispezione. "Andiamo a vedere un posto carino in valle" cambia prospettiva. Durante la visita, osservate reazioni non verbali: spalle rilassate, curiosità verso il giardino, domande sui pasti. Sono segnali più veri di un "va bene" detto per chiudere la conversazione.</p><p>Ricordate che autosufficienza non significa autosufficienza emotiva. Vostro padre può gestire la spesa e avere bisogno di compagnia a cena. Vostra madre può cucinare ancora bene e dimenticare di pranzare da sola. I bisogni convivono — non si annullano a vicenda.</p>""",

"autonomia-dignita-terza-eta": """<h2>Autonomia nella vita di ogni giorno</h2><p>In pratica, rispettare l'autonomia significa lasciar scegliere l'orario del bagno quando possibile, non imporre programmi televisivi comuni, chiedere permesso prima di entrare in camera se non c'è urgenza. Piccoli gesti che dicono: "Questa è ancora casa tua, anche se condivisa."</p><p>Per i figli, significa resistere all'impulso di decisione totalizzante. "Ho già firmato" senza coinvolgimento distrugge fiducia. "Ho trovato un posto che mi piacerebbe farti vedere" apre porta. La dignità del genitore passa anche dal modo in cui voi presentate la scelta.</p><p>Quando visitate Casa Famiglia Castelletto, osservate come operatori e ospiti interagiscono. Ton voce, distanza fisica, sorrisi: tutto comunica rispetto o controllo. Fidatevi di ciò che vedete più che delle brochure.</p><p>Autonomia e dignità non sono ideali astratti — sono ciò che vostro caro sente al risveglio. Merita di sentirsi persona intera, fino a quando possibile e oltre.</p>""",

"casa-famiglia-vs-rsa-differenze": """<h2>Quattro domande per orientarvi</h2><p>Prima di scegliere, ponetevi quattro domande semplici. Uno: mio padre o mia madre è ancora autosufficiente nelle attività base? Due: ha bisogno di cure infermieristiche quotidiane? Tre: resiste all'idea di ambiente istituzionale? Quattro: la solitudine è il problema principale? Se le risposte sono sì, no, sì, sì — la casa famiglia merita di essere esplorata seriamente.</p><p>Visitate entrambe le tipologie se avete dubbi. Confronto diretto vale più di cento articoli. Portate vostro caro quando possibile. Lasciategli tempo di assorbire, di fare domande, di esprimere preferenze senza giudizio.</p><p>Parlate con medico di famiglia: non per delegare la decisione, ma per allineare aspettative sanitarie realistiche. Un parere professionale integra il vostro amore senza sostituirlo.</p><h2>Coazze: una casa famiglia in Valle di Susa</h2><p>A Coazze accogliamo anziani autosufficienti in villa familiare, con giardino, pasti di casa, assistenza h24 discreta. Non siamo struttura sanitaria — siamo seconda casa per chi merita compagnia e sicurezza. Scoprite <a href="/servizi/">servizi</a>, <a href="/la-struttura/">spazi</a> e <a href="/contatti/">contatti</a>.</p><p><strong>Hai dubbi? Parliamone.</strong> Rispondiamo con onestà e calma — senza pressione commerciale.</p>""",

"coazze-giaveno-pinerolo-servizi": """<h2>Venire a trovarci</h2><p>Stradale Poirino 152 è facilmente individuabile. Parcheggio nelle vicinanze, accesso senza barriere eccessive. Avvisateci della visita così dedichiamo tempo senza fretta: tour degli spazi, conversazione, risposte a ogni domanda.</p><p>Portate elenco di dubbi scritti — è normale. Chiedete tutto: pasti, visite, camere, retta, tempi ingresso, cosa portare, come funziona la notte. Nessuna domanda è stupida quando si tratta di chi amate.</p><p>Se vostro caro viene con voi, rispettate i suoi tempi. Se preferisce restare in auto all'inizio, va bene. Forzare ingresso nella struttura può chiudere porte invece di aprirle. Pazienza e rispetto sono investimenti, non perdite di tempo.</p><p>Coazze vi aspetta — non come meta lontana, ma come possibilità concreta di serenità in valle.</p>""",

"costi-retta-casa-famiglia-piemonte": """<h2>Investimento nella serenità familiare</h2><p>Quando calcolate costi, includete anche ciò che oggi pagate invisibilmente: ore di permesso dal lavoro, benzina per visite d'emergenza, pranzi veloci portati a casa, notti insonni. La retta di una casa famiglia può assorbire parte di questo carico invisibile — non sostituisce voi, ma vi restituisce equilibrio.</p><p>Parlate tra fratelli prima, non dopo. Chi paga quanto, come, con quale cadenza. Documentate accordi semplici per iscritto — anche email tra fratelli — per evitare malintesi quando stress e stanchezza aumentano.</p><p>Chiedete a noi preventivo dettagliato e visitate. Confronto informato è diritto vostro e dovere nostro verso trasparenza.</p>""",

"domande-figli-casa-famiglia": """<h2>Altre domande che ci fanno spesso</h2><p><strong>Posso fidarmi del personale?</strong> Visitate, osservate, fate domande sul turnover, sulla formazione, su come segnalare problemi. Fiducia si costruisce — non si compra.</p><p><strong>Mio fratello non è d'accordo.</strong> Normalizzate il disaccordo. Proponete visita congiunta e tempo di riflessione. Decisioni affrettate divisive costano caro dopo.</p><p><strong>È reversibile?</strong> Ogni situazione è diversa. Parliamone con onestà fin dall'inizio — incluso cosa succede se i bisogni cambiano.</p><p>Non siete soli in queste domande. Ogni figlio che ci contatta porta un mix di amore, paura, stanchezza. È umano. È onesto. Meritate risposte chiare — e vostro caro merita ascolto.</p>""",

"inserimento-nuovo-ospite": """<h2>Checklist per il giorno del trasloco</h2><p>Documenti in ordine, farmaci etichettati, abiti stagione, elenco contatti emergenza, numeri medico e specialisti, preferenze alimentari scritte, oggetti affettivi concordati. Evitate di trasferire tutta la casa — portate ciò che fa dire "sono a casa".</p><p>Il vostro tono quel giorno conta enormemente. Ansia vostra si trasmette. Respirate, sorridete, dite verità con dolcezza: "Qui ci sono persone buone. Io torno presto. Non sei solo."</p><p>Nelle settimane successive, chiamate con regolarità breve — non solo visite maratonetiche. Un "ti voglio bene" al telefono a metà settimana vale quanto un pranzo domenicale.</p>""",

"valle-di-susa-vita-anziani": """<h2>Vivere bene, non solo vivere</h2><p>Terza età non è epilogo grigio — può essere capitolo di convivialità, natura, relazioni curate. In valle, molti anziani trovano ritmo che città non offre: meno rumore, più volti conosciuti, mercati riconoscibili, chiese e piazze come punti di riferimento emotivo.</p><p>Se vostro caro ama camminare piano, respirare aria buona, salutare vicini — valle sostiene queste abitudini meglio di un quartiere anonimo. Casa famiglia integra territorio e cura — non li oppone.</p><p>Invitiamo famiglie da tutta la valle a conoscerci. Prima conversazione sempre senza impegno.</p>""",

"visite-familiari-casa-famiglia": """<h2>Costruire rituali che restano</h2><p>Rituali rassicurano: caffè del sabato, telefonata del mercoledì, foto WhatsApp del nipote che gioca. Non servono grandi gesti — servono costanza. Vostro caro impara ad attendere e a fidarsi del ritorno.</p><p>Quando visitate, portate notizie del mondo esterno — non solo domande sulla salute. Raccontate del mercato, del tempo, della serie tv che guardate. Normalità condivide legame.</p><p>Se vivete lontano, coordinate con fratelli locali per continuità. Rete familiare distribuita evita buchi di presenza che alimentano solitudine.</p><p>Le visite sono regalo reciproco — non dovere espiatorio. Venite con cuore aperto, non solo con colpa in spalla.</p>""",
}

def wc(html):
    m = re.search(r'content-prose">(.*?)</div>\s*<aside', html, re.S)
    return len(re.findall(r'\w+', re.sub(r'<[^>]+>',' ', m.group(1)))) if m else 0

for slug, block in BLOCKS.items():
    path = os.path.join(BLOG, slug, 'index.html')
    if not os.path.exists(path): continue
    html = open(path, encoding='utf-8').read()
    if block[:40] not in html:
        html = html.replace('      </div>\n      <aside class="blog-article-cta">', block + '\n      </div>\n      <aside class="blog-article-cta">')
        open(path,'w',encoding='utf-8').write(html)
    print(f'{wc(html):4d} {slug}')
